#!/usr/bin/env bash

# Emits the latest N versions

set -eo pipefail
declare VERSIONS="${1:-5}"

#cat data.json \
npm info @sap/cds-dk --json \
    | jq --arg v "$VERSIONS" -r '.versions[$v | tonumber * -1:][]'




